#!/usr/bin/env python
import argparse
from os.path import dirname, basename, isfile, join
import glob


# Get a list of module names for argparse.
moduleDir = dirname(__file__) + "/modules"
modules   = glob.glob(moduleDir + '/*.py')
__all__   = [ basename(f)[:-3] for f in modules if isfile(f) and not f.endswith('__init__.py')]

def main():
    parser = argparse.ArgumentParser(description="A script with modules providing various disk utilities.")

    parser.add_argument(
            '-m',
            '--mode',
            choices=__all__,
            default='CheckErasure',
            help='Select a mode of operation.'
            )

    args, unknownargs = parser.parse_known_args()
    #args = parser.parse_args()

    #modulePath = "%s/%s.py" % (moduleDir,args.mode)
    modulePath = "%s.%s" % ('modules',args.mode)
    #exec("%s = __import__(%s)" % (args.mode, modulePath))
    #Mode = __import__(modulePath, fromlist=[None])
    #mode = Mode.CheckErasure()

    parser.parse_known_args()

    args.mode = __import__(modulePath, fromlist=[None])
    Mode = args.mode.CheckErasure()
    Mode.main()

if __name__ == "__main__":
    main()
